# Generated by Django 5.0.6 on 2024-05-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('about', models.CharField(max_length=500)),
                ('how_much', models.CharField(max_length=250)),
            ],
        ),
    ]
